# Generated by Django 5.2.7 on 2025-10-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pen',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pen',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
