# Generated by Django 5.2.7 on 2025-10-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0002_pen_on_sale_pen_quantity_pen_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen',
            name='quantity',
        ),
    ]
