# Generated by Django 5.2.7 on 2025-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0003_remove_pen_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
