# Generated by Django 5.2.7 on 2025-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0004_pen_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
