# Generated by Django 5.2.7 on 2025-10-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0005_pen_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('ballpoint', 'Ballpoint'), ('gel', 'Gel'), ('roller', 'Roller'), ('fountain', 'Fountain Ink Cartridge'), ('others', 'Others')], default='ballpoint', max_length=50)),
                ('size', models.CharField(help_text='Example: 0.5mm, 0.7mm, 13cm, Pilot G2-compatible, etc.', max_length=100)),
                ('compatible_pen', models.CharField(blank=True, help_text='Mention which pen models this refill fits (optional).', max_length=150, null=True)),
                ('ink_color', models.CharField(default='blue', help_text='Ink color, e.g. Blue, Black, Red', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='refills/')),
            ],
        ),
    ]
