# Generated by Django 5.2.7 on 2025-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0006_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
