# Generated by Django 5.2.7 on 2025-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0007_refill_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pen',
            name='category',
            field=models.CharField(choices=[('fountain', 'Fountain Pen'), ('ballpoint', 'Ballpoint Pen'), ('rollerball', 'Rollerball Pen'), ('gel', 'Gel Pen'), ('ink', 'Ink Pen'), ('vintage', 'Vintage Pen')], max_length=100),
        ),
        migrations.AlterField(
            model_name='refill',
            name='compatible_pen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='refill',
            name='ink_color',
            field=models.CharField(default='blue', max_length=30),
        ),
        migrations.AlterField(
            model_name='refill',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='refill',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
