# Generated by Django 5.2.7 on 2025-11-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0008_alter_pen_category_alter_refill_compatible_pen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
